---
- name: Create directory for archive
  file:
    path: /tmp/etcd
    state: directory
  tags: one

- name: Download etcd 
  get_url:
    url: "https://storage.googleapis.com/etcd/{{ distrib_version }}/etcd-{{ distrib_version }}-linux-amd64.tar.gz"
    dest: /tmp/etcd
  tags: one

- name: Unzip archive
  unarchive:
      src: "/tmp/etcd/etcd-{{ distrib_version }}-linux-amd64.tar.gz"
      dest: /tmp/etcd
      mode: 0755
      remote_src: yes

- name: Copy etcd files
  copy:
        src: "/tmp/etcd/etcd-{{ distrib_version }}-linux-amd64/{{ item }}"
        dest: /usr/local/bin/
        mode: 0755
        remote_src: yes
  loop:
        - etcd
        - etcdctl  

- name: Clean
  file:
    path: /tmp/etcd/
    state: absent

- name: Create user etcd
  user:
    name: etcd
    shell: /sbin/nologin
    system: yes

- name: Create dir for ETCD
  file:
    path: "{{ item  }}"
    state: directory
    owner: etcd
    group: etcd
  with_items:
    - '/etc/etcd'
    - '/var/lib/etcd'

- name: Create SystemD unit
  template:
          src: etcd.service.j2
          dest: /etc/systemd/system/etcd.service
          owner: root
          group: root
          mode: 0640
  notify:
          - reload etcd
